- name: Add NVIDIA PPA
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    update_cache: yes

- name: Install nvidia-driver package
  apt: name=nvidia-driver-{{ kube_nvidia_driver_version }}
  when: ansible_distribution_major_version|int >= 18

- name: Install nvidia package
  apt: name=nvidia-{{ kube_nvidia_driver_version }}
  when: ansible_distribution_major_version|int == 16

- name: Add nvidia-docker repo key
  apt_key:
    url: "https://nvidia.github.io/nvidia-docker/gpgkey"
    state: present

- name: Download nvidia-docker apt list
  get_url:
    url: https://nvidia.github.io/nvidia-docker/{{ansible_distribution | lower}}{{ansible_distribution_version}}/nvidia-docker.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list

- name: Ubuntu apt update
  apt: update_cache=yes

- name: Install nvidia-docker2 package
  apt: name=nvidia-docker2

- set_fact:
    docker_options: "{{ docker_options | combine(docker_nvidia_options) }}"