---
- name: Disable swap
  command: swapoff -a

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw.*)$'
    replace: '# \1'

- name: Check docker version
  shell: docker -v | cut -d ' ' -f 3 | cut -d ',' -f 1
  register: docker_output

- debug: msg="Docker version installed = {{ docker_output.stdout }}"

- name: Check kube version
  shell: kubeadm version -o short | cut -d 'v' -f 2
  register: kubeadm_output

- debug: msg="Kube version installed = {{ kubeadm_output.stdout }}"

- set_fact:
    docker_install: true

- name: Include "{{ansible_os_family}}" Kubernetes recipe
  include_tasks: "{{ansible_os_family}}.yaml"

- name: Include "{{kube_type_of_node}}" tasks
  include_tasks: "{{kube_type_of_node}}.yaml"

