---

- name: Wait for Kube master
  wait_for:
    path: /etc/environment
    search_regex: "KUBECONFIG="
  delegate_to: "{{kube_server}}"

- block:

  - name: read node token on k3s master node
    set_fact:
      node_token: "{{ lookup('file', '/var/lib/rancher/k3s/server/node-token') }}"

  - name: Install k3s node
    command: sh /tmp/k3s.sh creates=/var/lib/rancher/k3s/agent/etc/k3s-agent-load-balancer.json
    environment:
      INSTALL_K3S_EXEC: "{{kube_k3_exec}}"
      K3S_URL: https://{{ kube_server }}:6443
      K3S_TOKEN: "{{ node_token }}"

  when: kube_install_method == "k3s"

- block:

  - name: Add KUBELET_EXTRA_ARGS
    lineinfile:
      dest: "{{item}}/kubelet"
      line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=systemd {{kubelet_extra_args}}'
      regexp: 'KUBELET_EXTRA_ARGS='
      create: yes
    notify: restart kubelet
    with_first_found:
      - files:
        - /etc/sysconfig/
        - /etc/default/

  - name: Add node to kube cluster
    command: kubeadm join --token {{kube_token}} {{kube_server}}:6443 --discovery-token-unsafe-skip-ca-verification creates=/etc/kubernetes/kubelet.conf

  when: kube_install_method == "kubeadm"