---
- name: Wait for Kube master
  wait_for:
    path: /etc/environment
    search_regex: "KUBECONFIG=/etc/kubernetes/admin.conf"
  delegate_to: "{{kube_server}}"

- name: Add KUBELET_EXTRA_ARGS
  lineinfile:
    dest: "{{item}}"kubelet
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=systemd {{kubelet_extra_args}}'
    regexp: 'KUBELET_EXTRA_ARGS='
    create: yes
  notify: restart kubelet
  with_first_found:
    - files:
       - /etc/sysconfig/
       - /etc/default/

- name: Add node to kube cluster
  command: kubeadm join --token {{kube_token}} {{kube_server}}:6443 --discovery-token-unsafe-skip-ca-verification creates=/etc/kubernetes/kubelet.conf
