---
name: CI

on:

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install requisites
        run: sudo apt update && sudo apt install -y python3 python3-pip

      - name: install requisites
        run: sudo pip3 install ansible

      - name: Create ansible.cfg with correct roles_path
        run: sudo printf '[defaults]\nroles_path=../' > ansible.cfg
  
      - name: Install dependency
        run: sudo ansible-galaxy install grycap.ntp
  
      - name: Basic role syntax check
        run: sudo ansible-playbook tests/test.yml -i tests/inventory --syntax-check

      - name: Basic role check
        run: sudo ansible-playbook tests/test.yml -i tests/inventory